name: build
on: [ push, pull_request ]
jobs:
  applications:
    name: application ci/cd
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SPRING_OUTPUT_ANSI_ENABLED: DETECT
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '8.x'
      - name: Packaging application...
        run: |
          echo "<settings><servers><server><id>github</id><username>OWNER</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
          chmod +x mvnw
          ./mvnw -ntp clean package -Pgithub -DskipTests -e -U
      - name: Deploying application...
        run: |
          ./mvnw -ntp deploy -Pgithub -DskipTests -e -U
